export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAIL = "CREATE_BRAND_FAIL";
export const CREATE_BRAND_RESET = "CREATE_BRAND_RESET";

export const BRAND_LIST_REQUEST = "BRAND_LIST_REQUEST";
export const BRAND_LIST_SUCCESS = "BRAND_LIST_SUCCESS";
export const BRAND_LIST_FAIL = "BRAND_LIST_FAIL";
export const BRAND_LIST_RESET = "BRAND_LIST_RESET";

export const BRAND_DELETE_SUCCESS = "BRAND_DELETE_SUCCESS";
