export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_FAIL = "DASHBOARD_FAIL";

export const STATUS_ORDER_DELIVERED_SUCCESS = "STATUS_ORDER_DELIVERED_SUCCESS";

export const SUM_AMOUNT_SUCCESS = "SUM_AMOUNT_SUCCESS";
