export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const UPLOAD_IMG_REQUEST = "UPLOAD_IMG_REQUEST";
export const UPLOAD_IMG_SUCCESS = "UPLOAD_IMG_SUCCESS";
export const UPLOAD_IMG_FAIL = "UPLOAD_IMG_FAIL";

export const DELETE_IMG_SUCCESS = "DELETE_IMG_SUCCESS";
export const RESET_IMG = "RESET_IMG";

export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
